apiVersion: v1
kind: Namespace
metadata:
  name: nostrsearch
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nostrsearch-index
  namespace: nostrsearch
  labels:
    app.kubernetes.io/name: nostrsearch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  # storageClassName: standard   # set to your cluster's storage class
