apiVersion: v1
kind: Service
metadata:
  name: nostrsearch
  namespace: nostrsearch
  labels:
    app.kubernetes.io/name: nostrsearch
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nostrsearch
    app.kubernetes.io/component: server
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
